version: '3'
services:
  php:
    container_name: php-fpm
    image: php-fpm_i
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/usr/share/nginx/html/
    networks:
      - container-link

  nginx:
    container_name: nginx
    image: nginx_i
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    networks:
      - container-link
    depends_on:
      - php
    volumes:
      - ./src:/usr/share/nginx/html
      # - ./volume/nginx/log/:/var/log/nginx/

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    networks:
      - container-link
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: kenta
      MYSQL_PASSWORD: kenta
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./volume/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "4000:80"
    networks:
      - container-link
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal